### ISSUE TITLE
NoReturn vs None type

### ISSUE THREAD

**Issue by adam-tokarski** [guilatrova/python-async-scenarios#1]
Hi, thanks for your great articles.
I just wanted to note that `typing.NoReturn` is for cases when there will be no normal return from function. In your cases, like [here](https://github.com/guilatrova/python-async-scenarios/blob/main/API/client/sync.py#L26), you return `None` implicitly, so there should be `-> None` instead of `-> NoReturn` I guess. 

See this [PEP](https://www.python.org/dev/peps/pep-0484/#the-noreturn-type).

Thanks again!

**Comment by guilatrova** [comment]
Oh, good catch! You're right. 
Feel free to open a PR if you have some time (so people can know you contributed to this project ❤️ ).
Otherwise, I'll fix it later

**Comment by miahj1** [comment]
The changes should also be updated in the article; currently, it looks like:

![image](https://github.com/guilatrova/python-async-scenarios/assets/84815985/2ff5f799-8716-4354-9fd8-16eeb17671e9)
